# Mini Intro to Numpy
by Liang Jin

Part of AcF701 Python Sessions:
- [github.com/drliangjin/mini-python-book](https://github.com/drliangjin/mini-python-book)

## NumPy -- Numerical Python
One of the most important foundational package for numerical computing in Python.
- ndarray: multi-dimensional array
- mathematical functions
- linear algebra, random number generation, and so on

### Import Package

In [3]:
import numpy

In [4]:
# Python Convention
import numpy as np

NumPy based algorithes are generally **10** to **100** faster (or more) than pure Python algorithms

### NumPy ndarray Object

In [5]:
# Generate random data
# np ==> short for Numpy
# random ==> sub-module in Numpy
# randn ==> a function in sub-module, random, in Numpy
arr1 = np.random.randn(2, 3) # ==> 2 rows, 3 columns

In [6]:
arr1

array([[-1.31931127, -1.7074548 ,  0.754846  ],
       [-0.82358785,  0.20476979, -1.23841523]])

In [7]:
# basic attributes on the array
arr1.ndim, arr1.shape, arr1.dtype

(2, (2, 3), dtype('float64'))

### Creating ndarrays

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
# we can a specify data type
arr3 = np.array(data2, dtype=np.float64)
arr3

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [10]:
# or cast an array using astype method
arr4 = arr3.astype('int64')
arr3.dtype, arr4.dtype

(dtype('float64'), dtype('int64'))

### Arithmetic operations

In [11]:
# element-wise calculations
arr3 * 2

array([[ 2.,  4.,  6.,  8.],
       [10., 12., 14., 16.]])

In [12]:
# array-wise calculations
arr3 - arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Indexing and Slicing

In [14]:
# create an array using arange, similar to python's built-in range
arr = np.arange(10) # again, 10 elements from 0 to 9
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# retrieve element(s)
arr[5], arr[5:]

(5, array([5, 6, 7, 8, 9]))

In [18]:
# update element(s).
arr[5:] = -99
arr

array([  0,   1,   2,   3,   4, -99, -99, -99, -99, -99])

In [19]:
# WARNING: mutations, need to use .copy() method
arr_slice = arr[5:]
arr_slice[1]=-100
arr

### Boolean Indexing

In [30]:
data = np.random.randn(2,5)
data

array([[ 1.23962624, -0.41508516, -1.40192547,  0.25303811, -0.00538131],
       [ 2.26644996, -1.3524111 , -1.87090939,  2.10934498, -0.71874484]])

In [31]:
# create a new array which is booleans
cond = data <= 0
cond

array([[False,  True,  True, False,  True],
       [False,  True,  True, False,  True]])

In [32]:
# filter data using conditions
data_cond = data[cond]
data_cond

array([-0.41508516, -1.40192547, -0.00538131, -1.3524111 , -1.87090939,
       -0.71874484])