# Mini Intro to Numpy
by Liang Jin

Part of AcF701 Python Sessions:
- [github.com/drliangjin/mini-python-book](https://github.com/drliangjin/mini-python-book)

## NumPy -- Numerical Python
One of the most important foundational package for numerical computing in Python.
- ndarray: multi-dimensional array
- mathematical functions
- linear algebra, random number generation, and so on

### Import Package

In [1]:
import numpy

In [2]:
# Python Convention
import numpy as np

NumPy based algorithes are generally **10** to **100** faster (or more) than pure Python algorithms

### NumPy ndarray Object

In [10]:
# Generate random data
# np ==> short for Numpy
# random ==> sub-module in Numpy
# randn ==> a function in sub-module, random, in Numpy
arr1 = np.random.randn(2, 3) # ==> 2 rows, 3 columns

In [11]:
arr1

array([[-1.30042641,  0.76408372, -0.25417108],
       [ 1.1499629 , -0.79341426,  0.01754593]])

In [18]:
# basic attributes on the array
arr1.ndim, arr1.shape, arr1.dtype

(2, (2, 3), dtype('float64'))

### Creating ndarrays

In [25]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
# we can a specify data type
arr3 = np.array(data2, dtype=np.float64)
arr3

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [24]:
# or cast an array using astype method
arr4 = arr3.astype('int64')
arr3.dtype, arr4.dtype

(dtype('float64'), dtype('int64'))